<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Collection;
use App\Models\Product;
use App\Models\Subcategory;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $vestidos = Subcategory::where('sku_code', 'DRESS')->first();
        $blusas = Subcategory::where('sku_code', 'BLOUS')->first();
        $blazers = Subcategory::where('sku_code', 'BLAZR')->first();
        $saias = Subcategory::where('sku_code', 'SKIRT')->first();
        $conjuntos = Subcategory::where('sku_code', 'SETS')->first();
        $calcas = Subcategory::where('sku_code', 'PANTS')->first();
        $batas = Subcategory::where('sku_code', 'TUNIC')->first();
        $camisas = Subcategory::where('sku_code', 'SHIRT')->first();
        $fatos = Subcategory::where('sku_code', 'SWIMW')->first();
        $casacos = Subcategory::where('sku_code', 'JACKT')->first();

        $zara = Brand::where('slug', 'zara')->first();
        $shein = Brand::where('slug', 'shein')->first();
        $generico = Brand::where('slug', 'generico')->first();

        $verao = Collection::where('slug', 'verao-2026')->first();

        if (! $vestidos || ! $blusas) {
            $this->command->error('Subcategories not found. Run SubcategorySeeder first.');

            return;
        }

        $products = [
            // Vestidos
            [
                'sku' => 'DRESS-0001',
                'name' => 'Vestido Floral Midi Vermelho',
                'slug' => 'vestido-floral-midi-vermelho',
                'description' => 'Vestido midi com estampa floral em tons de vermelho. Tecido leve e fluido, perfeito para o clima angolano. Decote em V e manga curta.',
                'short_description' => 'Vestido midi floral vermelho, decote V, manga curta.',
                'subcategory_id' => $vestidos->id,
                'brand_id' => $zara?->id,
                'collection_id' => $verao?->id,
                'price_cost' => 8000.00,
                'price_sell' => 15000.00,
                'discount_percentage' => 0,
                'stock_min' => 3,
                'weight' => 250,
                'condition' => 'new',
                'is_active' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_trending' => true,
            ],
            [
                'sku' => 'DRESS-0002',
                'name' => 'Vestido Preto Elegante Longo',
                'slug' => 'vestido-preto-elegante-longo',
                'description' => 'Vestido longo preto elegante para eventos formais e festas. Tecido cetim com fenda lateral.',
                'short_description' => 'Vestido longo preto em cetim com fenda lateral.',
                'subcategory_id' => $vestidos->id,
                'brand_id' => $generico?->id,
                'price_cost' => 12000.00,
                'price_sell' => 22000.00,
                'discount_percentage' => 10,
                'stock_min' => 2,
                'weight' => 350,
                'condition' => 'new',
                'is_active' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_on_sale' => true,
            ],
            [
                'sku' => 'DRESS-0003',
                'name' => 'Vestido Azul Marinho Wrap',
                'slug' => 'vestido-azul-marinho-wrap',
                'description' => 'Vestido wrap em azul marinho, perfeito para o trabalho. Tecido jersey suave e elegante.',
                'short_description' => 'Vestido wrap azul marinho, elegante.',
                'subcategory_id' => $vestidos->id,
                'brand_id' => $shein?->id,
                'price_cost' => 6000.00,
                'price_sell' => 12500.00,
                'discount_percentage' => 0,
                'stock_min' => 4,
                'weight' => 280,
                'condition' => 'new',
                'is_active' => true,
                'is_new' => true,
            ],
            [
                'sku' => 'DRESS-0004',
                'name' => 'Vestido Estampado Verão',
                'slug' => 'vestido-estampado-verao',
                'description' => 'Vestido leve com estampa tropical colorida. Perfeito para dias quentes.',
                'short_description' => 'Vestido leve estampado tropical.',
                'subcategory_id' => $vestidos->id,
                'brand_id' => $generico?->id,
                'price_cost' => 4500.00,
                'price_sell' => 8900.00,
                'discount_percentage' => 20,
                'stock_min' => 5,
                'weight' => 200,
                'condition' => 'new',
                'is_active' => true,
                'is_on_sale' => true,
            ],
            // Blusas
            [
                'sku' => 'BLOUS-0001',
                'name' => 'Blusa Branca Cropped Algodão',
                'slug' => 'blusa-branca-cropped-algodao',
                'description' => 'Blusa cropped em algodão branco. Confortável e versátil para o dia a dia.',
                'short_description' => 'Blusa cropped branca em algodón.',
                'subcategory_id' => $blusas->id,
                'brand_id' => $shein?->id,
                'collection_id' => $verao?->id,
                'price_cost' => 3000.00,
                'price_sell' => 6500.00,
                'discount_percentage' => 0,
                'stock_min' => 5,
                'weight' => 120,
                'condition' => 'new',
                'is_active' => true,
                'is_new' => true,
            ],
            [
                'sku' => 'BLOUS-0002',
                'name' => 'Blusa Preta Manga Bufante',
                'slug' => 'blusa-preta-manga-bufante',
                'description' => 'Blusa elegante com manga bufante. Perfeita para festas e eventos.',
                'short_description' => 'Blusa preta com manga bufante.',
                'subcategory_id' => $blusas->id,
                'brand_id' => $zara?->id,
                'price_cost' => 5500.00,
                'price_sell' => 11000.00,
                'discount_percentage' => 15,
                'stock_min' => 3,
                'weight' => 180,
                'condition' => 'new',
                'is_active' => true,
                'is_featured' => true,
                'is_on_sale' => true,
            ],
            [
                'sku' => 'BLOUS-0003',
                'name' => 'Blusa Bege Gola Alta',
                'slug' => 'blusa-bege-gola-alta',
                'description' => 'Blusa elegante com gola alta em tom bege. Versátil para trabalho.',
                'short_description' => 'Blusa bege com gola alta.',
                'subcategory_id' => $blusas->id,
                'brand_id' => $shein?->id,
                'price_cost' => 3500.00,
                'price_sell' => 7500.00,
                'discount_percentage' => 0,
                'stock_min' => 4,
                'weight' => 150,
                'condition' => 'new',
                'is_active' => true,
                'is_trending' => true,
            ],
            [
                'sku' => 'BLOUS-0004',
                'name' => 'Blusa Verde Musgo Elegante',
                'slug' => 'blusa-verde-musgo-elegante',
                'description' => 'Blusa em verde musgo com corte moderno. Perfeita para o escritório.',
                'short_description' => 'Blusa verde musgo moderna.',
                'subcategory_id' => $blusas->id,
                'brand_id' => $generico?->id,
                'price_cost' => 4000.00,
                'price_sell' => 8500.00,
                'discount_percentage' => 0,
                'stock_min' => 3,
                'weight' => 160,
                'condition' => 'new',
                'is_active' => true,
                'is_new' => true,
            ],
            // Blazers
            [
                'sku' => 'BLAZR-0001',
                'name' => 'Blazer Oversized Bege',
                'slug' => 'blazer-oversized-bege',
                'description' => 'Blazer oversized em tom bege neutro. Corte moderno e descontraído.',
                'short_description' => 'Blazer oversized bege.',
                'subcategory_id' => $blazers?->id ?? $vestidos->id,
                'brand_id' => $zara?->id,
                'price_cost' => 10000.00,
                'price_sell' => 18500.00,
                'discount_percentage' => 0,
                'stock_min' => 2,
                'weight' => 400,
                'condition' => 'new',
                'is_active' => true,
                'is_featured' => true,
                'is_new' => true,
            ],
            [
                'sku' => 'BLAZR-0002',
                'name' => 'Blazer Preto Clássico',
                'slug' => 'blazer-preto-classico',
                'description' => 'Blazer clássico preto, essencial no guarda-roupa. Perfeito para o trabalho.',
                'short_description' => 'Blazer preto clássico.',
                'subcategory_id' => $blazers?->id ?? $vestidos->id,
                'brand_id' => $generico?->id,
                'price_cost' => 8000.00,
                'price_sell' => 15000.00,
                'discount_percentage' => 10,
                'stock_min' => 3,
                'weight' => 450,
                'condition' => 'new',
                'is_active' => true,
                'is_on_sale' => true,
            ],
            // Saias
            [
                'sku' => 'SKIRT-0001',
                'name' => 'Saia Midi Plissada Preta',
                'slug' => 'saia-midi-plissada-preta',
                'description' => 'Saia midi plissada em tecido leve preto. Elegante e versátil.',
                'short_description' => 'Saia midi plissada preta.',
                'subcategory_id' => $saias?->id ?? $vestidos->id,
                'brand_id' => $generico?->id,
                'price_cost' => 5000.00,
                'price_sell' => 9500.00,
                'discount_percentage' => 15,
                'stock_min' => 3,
                'weight' => 180,
                'condition' => 'new',
                'is_active' => true,
                'is_on_sale' => true,
            ],
            [
                'sku' => 'SKIRT-0002',
                'name' => 'Saia Jeans Midi Clara',
                'slug' => 'saia-jeans-midi-clara',
                'description' => 'Saia jeans clara com wash moderno.look casual.',
                'short_description' => 'Saia jeans clara midi.',
                'subcategory_id' => $saias?->id ?? $vestidos->id,
                'brand_id' => $shein?->id,
                'price_cost' => 4500.00,
                'price_sell' => 8900.00,
                'discount_percentage' => 0,
                'stock_min' => 4,
                'weight' => 350,
                'condition' => 'new',
                'is_active' => true,
                'is_new' => true,
            ],
            // Conjuntos
            [
                'sku' => 'SETS-0001',
                'name' => 'Conjunto Blazer + Calça Bege',
                'slug' => 'conjunto-blazer-calca-bege',
                'description' => 'Conjunto elegante blazer e calça em tom bege. Perfeito para o trabalho.',
                'short_description' => 'Conjunto blazer e calça bege.',
                'subcategory_id' => $conjuntos?->id ?? $calcas->id,
                'brand_id' => $zara?->id,
                'price_cost' => 15000.00,
                'price_sell' => 28000.00,
                'discount_percentage' => 0,
                'stock_min' => 2,
                'weight' => 800,
                'condition' => 'new',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'sku' => 'SETS-0002',
                'name' => 'Conjunto Top + Saia Floral',
                'slug' => 'conjunto-top-saia-floral',
                'description' => 'Conjunto coordenado top e saia com estampa floral tropical.',
                'short_description' => 'Conjunto top e saia floral.',
                'subcategory_id' => $conjuntos?->id ?? $calcas->id,
                'brand_id' => $shein?->id,
                'price_cost' => 5500.00,
                'price_sell' => 10500.00,
                'discount_percentage' => 20,
                'stock_min' => 3,
                'weight' => 280,
                'condition' => 'new',
                'is_active' => true,
                'is_on_sale' => true,
            ],
            // Calças
            [
                'sku' => 'PANTS-0001',
                'name' => 'Calça Wide Leg Preta',
                'slug' => 'calca-wide-leg-preta',
                'description' => 'Calça wide leg em preto elegante. Corte moderno e confortável.',
                'short_description' => 'Calça wide leg preta.',
                'subcategory_id' => $calcas?->id ?? $conjuntos->id,
                'brand_id' => $zara?->id,
                'price_cost' => 7000.00,
                'price_sell' => 14000.00,
                'discount_percentage' => 0,
                'stock_min' => 3,
                'weight' => 400,
                'condition' => 'new',
                'is_active' => true,
                'is_trending' => true,
            ],
            [
                'sku' => 'PANTS-0002',
                'name' => 'Calça Jeans Skinny Azul',
                'slug' => 'calca-jeans-skinny-azul',
                'description' => 'Calça jeans skinny em wash azul clássico. Essential wardrobe.',
                'short_description' => 'Calça jeans skinny azul.',
                'subcategory_id' => $calcas?->id ?? $conjuntos->id,
                'brand_id' => $shein?->id,
                'price_cost' => 5000.00,
                'price_sell' => 9500.00,
                'discount_percentage' => 15,
                'stock_min' => 5,
                'weight' => 450,
                'condition' => 'new',
                'is_active' => true,
                'is_on_sale' => true,
            ],
            // Batas
            [
                'sku' => 'TUNIC-0001',
                'name' => 'Bata Tradicional Africana Estampada',
                'slug' => 'bata-tradicional-africana-estampada',
                'description' => 'Bata tradicional africana com estampa colorida. Confortável e elegante.',
                'short_description' => 'Bata africana estampada.',
                'subcategory_id' => $batas?->id ?? $blusas->id,
                'brand_id' => $generico?->id,
                'price_cost' => 6000.00,
                'price_sell' => 12000.00,
                'discount_percentage' => 0,
                'stock_min' => 3,
                'weight' => 300,
                'condition' => 'new',
                'is_active' => true,
                'is_featured' => true,
            ],
            // Camisas
            [
                'sku' => 'SHIRT-0001',
                'name' => 'Camisa Branca Oversized',
                'slug' => 'camisa-branca-oversized',
                'description' => 'Camisa branca oversized em tecido leve. Perfeita para o verão.',
                'short_description' => 'Camisa branca oversized.',
                'subcategory_id' => $camisas?->id ?? $blusas->id,
                'brand_id' => $shein?->id,
                'price_cost' => 3500.00,
                'price_sell' => 7500.00,
                'discount_percentage' => 0,
                'stock_min' => 4,
                'weight' => 180,
                'condition' => 'new',
                'is_active' => true,
                'is_new' => true,
            ],
            [
                'sku' => 'SHIRT-0002',
                'name' => 'Camisa Jeans Clara',
                'slug' => 'camisa-jeans-clara',
                'description' => 'Camisa jeans em wash claro. Look casual despojado.',
                'short_description' => 'Camisa jeans clara.',
                'subcategory_id' => $camisas?->id ?? $blusas->id,
                'brand_id' => $generico?->id,
                'price_cost' => 4000.00,
                'price_sell' => 8000.00,
                'discount_percentage' => 10,
                'stock_min' => 3,
                'weight' => 250,
                'condition' => 'new',
                'is_active' => true,
                'is_on_sale' => true,
            ],
            // Fatos de Banho
            [
                'sku' => 'SWIM-0001',
                'name' => 'Fato de Banho Inteiro Preto',
                'slug' => 'fato-de-banho-inteiro-preto',
                'description' => 'Fato de banho inteiro elegante em preto. Perfeito para a praia.',
                'short_description' => 'Fato de banho inteiro preto.',
                'subcategory_id' => $fatos?->id ?? $vestidos->id,
                'brand_id' => $shein?->id,
                'price_cost' => 4000.00,
                'price_sell' => 8500.00,
                'discount_percentage' => 0,
                'stock_min' => 4,
                'weight' => 200,
                'condition' => 'new',
                'is_active' => true,
                'is_new' => true,
            ],
            // Casacos
            [
                'sku' => 'JACK-0001',
                'name' => 'Casaco Teddy Bege',
                'slug' => 'casaco-teddy-bege',
                'description' => 'Casaco teddy em tom bege. Quente e fashion para o inverno.',
                'short_description' => 'Casaco teddy bege.',
                'subcategory_id' => $casacos?->id ?? $blazers->id,
                'brand_id' => $zara?->id,
                'price_cost' => 12000.00,
                'price_sell' => 25000.00,
                'discount_percentage' => 0,
                'stock_min' => 2,
                'weight' => 800,
                'condition' => 'new',
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => true,
            ],
            [
                'sku' => 'JACK-0002',
                'name' => 'Jaqueta Jeans Azul',
                'slug' => 'jaqueta-jeans-azul',
                'description' => 'Jaqueta jeans em azul clássico.look atemporal.',
                'short_description' => 'Jaqueta jeans azul.',
                'subcategory_id' => $casacos?->id ?? $blazers->id,
                'brand_id' => $shein?->id,
                'price_cost' => 6500.00,
                'price_sell' => 13000.00,
                'discount_percentage' => 15,
                'stock_min' => 3,
                'weight' => 600,
                'condition' => 'new',
                'is_active' => true,
                'is_on_sale' => true,
            ],
        ];

        foreach ($products as $data) {
            Product::query()->updateOrCreate(
                ['sku' => $data['sku']],
                array_merge([
                    'is_active' => true,
                    'is_featured' => false,
                    'is_new' => false,
                    'is_trending' => false,
                    'is_bestseller' => false,
                    'is_on_sale' => false,
                    'published_at' => now(),
                    'views_count' => 0,
                    'sales_count' => 0,
                ], $data),
            );
        }

        $this->command->info('Seeded '.count($products).' products successfully!');
    }
}
